name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: [enhancement]
assignees: []

body:
  - type: textarea
    id: proposal
    attributes:
      label: Feature description
      description: What would you like to see added or improved?
      placeholder: Add support for multiple simultaneous input files...
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: How would this feature help you or others?
